# Generated by Django 4.2.7 on 2023-12-18 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_details',
            fields=[
                ('predict_id', models.AutoField(primary_key=True, serialize=False)),
                ('Field_1', models.CharField(max_length=60, null=True)),
                ('Field_2', models.CharField(max_length=60, null=True)),
                ('Field_3', models.TextField(max_length=60, null=True)),
                ('Field_4', models.CharField(max_length=60, null=True)),
                ('Field_5', models.CharField(max_length=60, null=True)),
                ('Field_6', models.CharField(max_length=60, null=True)),
                ('Field_7', models.CharField(max_length=60, null=True)),
                ('Field_8', models.TextField(max_length=60, null=True)),
            ],
            options={
                'db_table': 'predict_detail',
            },
        ),
        migrations.CreateModel(
            name='UploadModels',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dataset', models.FileField(null=True, upload_to='')),
                ('File_size', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upload_dataset',
            },
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(max_length=50, null=True)),
                ('contact', models.TextField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.TextField(max_length=8, null=True)),
                ('file', models.FileField(null=True, upload_to='images')),
                ('user_status', models.TextField(default='pending', max_length=30, null=True)),
                ('Otp_Status', models.TextField(default='pending', max_length=20)),
                ('otp', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='UserFeedbackModels',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_feedback', models.TextField(max_length=900)),
                ('star_rating', models.CharField(max_length=100, null=True)),
                ('star_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sentment', models.TextField(max_length=20, null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodels')),
            ],
            options={
                'db_table': 'feedback_Details',
            },
        ),
    ]
